## Numpy - Numerical Python

In [2]:
import numpy as np

In [3]:
#in numpy we deal with arrays and matrices at any point of time

In [4]:
l = [1,2,3,4]

In [5]:
ar = np.array(l)
#np.array() is used to convert list into array.

In [6]:
#array is a superclass in numpy

In [7]:
type(ar)

numpy.ndarray

In [8]:
#n-d-array means n-dimensional-array here it is 1D array, we need only one axis to represent it.

In [9]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [10]:
#above is 2 D array. We need 2 axis to represent it.

In [11]:
np.asarray(l) #also performs the task of converting list as array.

array([1, 2, 3, 4])

In [12]:
a = [2,3,4]

In [13]:
np.asarray(a)

array([2, 3, 4])

In [14]:
b = np.matrix(l)

In [15]:
b

matrix([[1, 2, 3, 4]])

In [16]:
#matrix is a subset of array. Matrix bydefault is 2Dimensional.

In [17]:
np.asanyarray(b)

matrix([[1, 2, 3, 4]])

In [18]:
#it does not convert the matrix in the array. Asarray function changes to any form of array.
# and matrix is also a type/form of array.

In [19]:
a = np.array(l)

In [20]:
a

array([1, 2, 3, 4])

In [21]:
c = a    # It is a shallow copy.
#when we write c = a then in our system the new variable also points or references the same data and does not create
#a copy of the data Hence any change made using any of the instances has an effect on the other instance pointing the
# same array/object

In [22]:
c

array([1, 2, 3, 4])

In [23]:
a

array([1, 2, 3, 4])

In [24]:
c[0]

1

In [25]:
c[0] = 100

In [26]:
c

array([100,   2,   3,   4])

In [27]:
a

array([100,   2,   3,   4])

In [28]:
d = np.copy(a)   # this is called as deep copy.
#when we create a copy of the array we allot new space in the system and store the value of the array.
# so when we make changes in the copy the original is not effected and vice versa

In [29]:
d

array([100,   2,   3,   4])

In [30]:
a[1] = 400

In [31]:
a

array([100, 400,   3,   4])

In [32]:
d

array([100,   2,   3,   4])

# Exploring Functions in Numpy

In [33]:
np.fromfunction(lambda i,j : i == j,(3,3)) # to generate an array from the function

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [34]:
np.fromfunction(lambda i,j : i*j,(3,3)) 

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [35]:
iterable = (i*i for i in range(5))

In [36]:
np.fromiter(iterable,float) #to generate an array from an iterable object

array([ 0.,  1.,  4.,  9., 16.])

In [37]:
np.fromstring("234 256 ",sep = ' ') # to generate an array from a string seperated by a delimiter which may be space

array([234., 256.])

In [38]:
np.fromstring('4,5',sep = ',') # here the delimiter is coma

array([4., 5.])

# Numpy Data Types

In [39]:
l = [2,3,4,5,6]

In [40]:
ar = np.array(l)

In [41]:
ar

array([2, 3, 4, 5, 6])

In [42]:
ar.ndim # to get the dimensional of array.

1

In [43]:
ar2 = np.array([[1,2,3,4,5],[2,5,6,8,7]]) 

In [44]:
ar2

array([[1, 2, 3, 4, 5],
       [2, 5, 6, 8, 7]])

In [45]:
ar2.ndim

2

In [46]:
ar2.size # returns the number of elements in the array.

10

In [47]:
ar.size

5

In [48]:
ar.shape

(5,)

In [49]:
ar2.shape # returns the number of rows and columns in format (rows,columns)

(2, 5)

In [50]:
ar.dtype #return the data type of the elements in the array.

dtype('int64')

In [51]:
ar2.dtype

dtype('int64')

In [52]:
ar22 = np.array([(1.4,45,45),(23,45,66)])

In [53]:
ar22

array([[ 1.4, 45. , 45. ],
       [23. , 45. , 66. ]])

In [54]:
ar22.dtype

dtype('float64')

In [55]:
ar22.size

6

In [56]:
ar22.shape

(2, 3)

In [61]:
list(range(5)) #the list function does not give float number in return, neither it support jumps 
#of floating point number

[0, 1, 2, 3, 4]

In [63]:
np.arange(2.3,5.6) # python numpy function of a-range() helps to generate floating point numbers
# also the jump can be adjusted.

array([2.3, 3.3, 4.3, 5.3])

In [65]:
np.arange(2.3,5.6,.3) # here we have given the jump of 0.3

array([2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7, 5. , 5.3])

In [67]:
list(np.arange(2.3,5.6,0.3))

[2.3,
 2.5999999999999996,
 2.8999999999999995,
 3.1999999999999993,
 3.499999999999999,
 3.799999999999999,
 4.099999999999999,
 4.399999999999999,
 4.699999999999998,
 4.999999999999998,
 5.299999999999998]

In [71]:
np.linspace(1,5,10) # this function produces 10 data between the given range

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [72]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [76]:
np.zeros((3,5)) # here we specify rows and columns

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [77]:
ar4 = np.zeros((3,4,5)) # we read this 3Dimensional arraqys as
# we have 3,  4*5 matrices

In [78]:
ar4

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [79]:
ar4.ndim

3

In [80]:
ar4.shape

(3, 4, 5)

In [81]:
np.ones(4)

array([1., 1., 1., 1.])

In [82]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [84]:
on = np.ones((2,3,2))

In [85]:
on

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [91]:
on + 5 # normal arithmetic operations can be performed on the matrix

array([[[6., 6.],
        [6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.],
        [6., 6.]]])

In [92]:
on * 4

array([[[4., 4.],
        [4., 4.],
        [4., 4.]],

       [[4., 4.],
        [4., 4.],
        [4., 4.]]])

In [93]:
on

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [94]:
np.empty((3,5)) # to createan empty matrix with the speciffied number of rows and columns

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [95]:
np.eye(4) # to create identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [96]:
np.linspace(2,4,20) # it produces the data between the set range and accoding to the no of data specified

array([2.        , 2.10526316, 2.21052632, 2.31578947, 2.42105263,
       2.52631579, 2.63157895, 2.73684211, 2.84210526, 2.94736842,
       3.05263158, 3.15789474, 3.26315789, 3.36842105, 3.47368421,
       3.57894737, 3.68421053, 3.78947368, 3.89473684, 4.        ])

In [99]:
np.logspace(2,5,10) #it produces the data between the range and according to the number of elements specified
#but also calculates the log value and returns the log value of the elements
#by default the base is 10 but can be changed using the base parameter.

array([   100.        ,    215.443469  ,    464.15888336,   1000.        ,
         2154.43469003,   4641.58883361,  10000.        ,  21544.34690032,
        46415.88833613, 100000.        ])

In [100]:
np.logspace(2,5,20, base =2)

array([ 4.        ,  4.46263167,  4.97877036,  5.55460457,  6.19703857,
        6.91377515,  7.71340798,  8.60552469,  9.60082176, 10.71123281,
       11.95007169, 13.3321921 , 14.87416568, 16.59448071, 18.5137638 ,
       20.65502717, 23.0439446 , 25.70915925, 28.68262708, 32.        ])

In [107]:
arr = np.random.randn(3,4) # it is used to generate random data and also to store it in the desired matrix
# it generates such data where the mean of the data is zero and std is 1 which is called as standard normaldistribution

In [108]:
arr

array([[ 1.09622947,  0.71643836, -0.09472175, -0.2819077 ],
       [-1.13017614, -0.80483782, -0.12790546,  0.3916549 ],
       [ 0.86589652,  0.83910394, -1.69191389, -0.75929992]])

In [109]:
import pandas as pd

In [110]:
pd.DataFrame(arr)

0         1         2         3
0  1.096229  0.716438 -0.094722 -0.281908
1 -1.130176 -0.804838 -0.127905  0.391655
2  0.865897  0.839104 -1.691914 -0.759300

In [112]:
np.random.rand(3,4) # it produces random data

array([[0.31280711, 0.9465239 , 0.75513313, 0.50061798],
       [0.6846389 , 0.68679533, 0.33883994, 0.44886573],
       [0.31368736, 0.13514222, 0.99296864, 0.24962208]])

In [113]:
np.random.randint(1,110,(3,4))

array([[24, 26,  7, 82],
       [21, 23, 26,  6],
       [88, 78, 45, 82]])

In [115]:
pd.DataFrame(np.random.randint(1,110,(300,500))).to_csv('test.csv')

In [116]:
arr = np.random.rand(3,4)

In [117]:
arr

array([[0.40648865, 0.4898445 , 0.01909951, 0.10630943],
       [0.46509991, 0.62843786, 0.91267973, 0.42143455],
       [0.07752393, 0.25691501, 0.0320082 , 0.964839  ]])

In [119]:
arr.reshape(6,2)  # to change the number of rows and columns for representation of data keeping the data same.

array([[0.40648865, 0.4898445 ],
       [0.01909951, 0.10630943],
       [0.46509991, 0.62843786],
       [0.91267973, 0.42143455],
       [0.07752393, 0.25691501],
       [0.0320082 , 0.964839  ]])

In [120]:
arr1 = arr.reshape(6,-13145523)

In [121]:
arr1

array([[0.40648865, 0.4898445 ],
       [0.01909951, 0.10630943],
       [0.46509991, 0.62843786],
       [0.91267973, 0.42143455],
       [0.07752393, 0.25691501],
       [0.0320082 , 0.964839  ]])

In [122]:
arr[1,1]

0.6284378615944812

In [123]:
arr1[1,1]

0.10630942690367473

In [125]:
arr1[1]

array([0.01909951, 0.10630943])

In [126]:
arr1[1][1]

0.10630942690367473

In [128]:
arr1[2:5,1]

array([0.62843786, 0.42143455, 0.25691501])

In [129]:
arr = np.random.randint(1,100,(5,5))

In [130]:
arr

array([[13, 30, 24,  7, 24],
       [ 6, 23, 85, 48, 41],
       [30, 32, 49, 68, 61],
       [59, 24, 54, 10,  8],
       [79, 61, 13, 31, 65]])

In [132]:
arr[arr > 50]

array([85, 68, 61, 59, 54, 79, 61, 65])

In [139]:
arr[2:4,[1,2]]

array([[32, 49],
       [24, 54]])

In [140]:
arr[0][0] 

13

In [141]:
arr[0][0] = 2000

In [142]:
arr[0][0]

2000

In [143]:
arr

array([[2000,   30,   24,    7,   24],
       [   6,   23,   85,   48,   41],
       [  30,   32,   49,   68,   61],
       [  59,   24,   54,   10,    8],
       [  79,   61,   13,   31,   65]])

In [144]:
arr1 = np.random.randint(1,3,(3,3))

In [145]:
arr2 = np.random.randint(1,3,(3,3))

In [146]:
arr1

array([[2, 2, 1],
       [2, 2, 2],
       [2, 1, 1]])

In [147]:
arr2

array([[2, 2, 1],
       [1, 1, 1],
       [2, 2, 2]])

In [148]:
arr1 + arr2

array([[4, 4, 2],
       [3, 3, 3],
       [4, 3, 3]])

In [149]:
arr1 / arr2

array([[1. , 1. , 1. ],
       [2. , 2. , 2. ],
       [1. , 0.5, 0.5]])

In [150]:
arr1 * arr2 # this is not matrix multiplication it is just normal index to index multiplication

array([[4, 4, 1],
       [2, 2, 2],
       [4, 2, 2]])

In [152]:
arr1 @ arr2  # to perform matrix multiplication we use the symbol @

array([[ 8,  8,  6],
       [10, 10,  8],
       [ 7,  7,  5]])

In [153]:
arr1/0

/tmp/ipykernel_77/1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [154]:
arr1 +100

array([[102, 102, 101],
       [102, 102, 102],
       [102, 101, 101]])

In [155]:
arr1**2

array([[4, 4, 1],
       [4, 4, 4],
       [4, 1, 1]])

# Broadcasting of Array - Numpy

In [158]:
arr = np.zeros((4,4))

In [159]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [160]:
row = np.array([1,2,3,4])

In [161]:
row

array([1, 2, 3, 4])

In [162]:
arr +row

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [163]:
row.ndim

1

In [164]:
row.shape

(4,)

In [166]:
row.T # to transpose.

array([1, 2, 3, 4])

In [170]:
col = np.array([[1,2,3,4]])

In [171]:
col

array([[1, 2, 3, 4]])

In [173]:
col.T

array([[1],
       [2],
       [3],
       [4]])

In [174]:
col.T + arr

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [175]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [177]:
arr1 = np.random.randint(1,4,(3,4))

In [178]:
arr1

array([[3, 2, 1, 3],
       [2, 2, 2, 2],
       [1, 3, 3, 3]])

In [179]:
np.sqrt(arr1)

array([[1.73205081, 1.41421356, 1.        , 1.73205081],
       [1.41421356, 1.41421356, 1.41421356, 1.41421356],
       [1.        , 1.73205081, 1.73205081, 1.73205081]])

In [180]:
np.exp(arr1)

array([[20.08553692,  7.3890561 ,  2.71828183, 20.08553692],
       [ 7.3890561 ,  7.3890561 ,  7.3890561 ,  7.3890561 ],
       [ 2.71828183, 20.08553692, 20.08553692, 20.08553692]])

In [181]:
np.log10(arr1)

array([[0.47712125, 0.30103   , 0.        , 0.47712125],
       [0.30103   , 0.30103   , 0.30103   , 0.30103   ],
       [0.        , 0.47712125, 0.47712125, 0.47712125]])