# Numpy Array manipulation

In [3]:
import numpy as np

In [4]:
arr = np.random.randint(1,10,(3,4))

In [5]:
arr

array([[4, 2, 2, 8],
       [5, 3, 3, 8],
       [8, 4, 7, 3]])

In [6]:
arr.reshape(6,2)

array([[4, 2],
       [2, 8],
       [5, 3],
       [3, 8],
       [8, 4],
       [7, 3]])

In [7]:
arr.reshape(2,6)

array([[4, 2, 2, 8, 5, 3],
       [3, 8, 8, 4, 7, 3]])

In [8]:
arr.reshape(1,12)

array([[4, 2, 2, 8, 5, 3, 3, 8, 8, 4, 7, 3]])

In [9]:
arr.reshape(12,1)

array([[4],
       [2],
       [2],
       [8],
       [5],
       [3],
       [3],
       [8],
       [8],
       [4],
       [7],
       [3]])

In [10]:
arr.T

array([[4, 5, 8],
       [2, 3, 4],
       [2, 3, 7],
       [8, 8, 3]])

In [13]:
arr.flatten() # converts the multi dimensional data into 1 dimension

array([4, 2, 2, 8, 5, 3, 3, 8, 8, 4, 7, 3])

In [14]:
arr1 = np.array([1,2,3,3,4])

In [15]:
arr1.ndim

1

In [16]:
np.expand_dims(arr1, axis = 1) #used to expand the dimension across the column axis = 1

array([[1],
       [2],
       [3],
       [3],
       [4]])

In [17]:
np.expand_dims(arr1, axis =0) # used to expand the dimension of array across the row. axis = 0 for rows

array([[1, 2, 3, 3, 4]])

In [18]:
arr

array([[4, 2, 2, 8],
       [5, 3, 3, 8],
       [8, 4, 7, 3]])

In [24]:
np.squeeze(arr) # here the squeeze function does not work because the list inside the array contains multiple 
#elements

array([[4, 2, 2, 8],
       [5, 3, 3, 8],
       [8, 4, 7, 3]])

In [25]:
data = np.array([[1],[2],[3]])

In [26]:
data

array([[1],
       [2],
       [3]])

In [27]:
np.squeeze(data) # here using the squeeze function shrinks the size of arrAY TO 1 DIMENSIONAL.

array([1, 2, 3])

In [28]:
np.repeat(arr1, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4, 4])

In [29]:
np.roll(arr1,2)

array([3, 4, 1, 2, 3])

In [30]:
arr1

array([1, 2, 3, 3, 4])

In [31]:
np.diag(arr1)

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4]])

# Numpy - Binary Operations

In [32]:
arr1 = np.random.randint(1,10,(3,4))

In [33]:
arr2 = np.random.randint(1,10,(3,4))

In [34]:
arr1 + arr2

array([[ 4, 16, 17, 11],
       [ 8, 11, 12,  7],
       [12, 12, 10, 10]])

In [35]:
arr1 * arr2

array([[ 4, 63, 72, 24],
       [12, 24, 27, 12],
       [27, 27, 24, 25]])

In [36]:
arr1/arr2

array([[1.        , 0.77777778, 0.88888889, 2.66666667],
       [3.        , 2.66666667, 3.        , 1.33333333],
       [3.        , 0.33333333, 0.66666667, 1.        ]])

In [37]:
arr1 - arr2

array([[ 0, -2, -1,  5],
       [ 4,  5,  6,  1],
       [ 6, -6, -2,  0]])

In [38]:
arr1% arr2

array([[0, 7, 8, 2],
       [0, 2, 0, 1],
       [0, 3, 4, 0]])

In [39]:
arr1**arr2

array([[        4,  40353607, 134217728,       512],
       [       36,       512,       729,        64],
       [      729,     19683,      4096,      3125]])

In [41]:
~arr1 # This is a negate operation on an array

array([[ -3,  -8,  -9,  -9],
       [ -7,  -9, -10,  -5],
       [-10,  -4,  -5,  -6]])

In [42]:
arr1 | arr2

array([[ 2, 15,  9, 11],
       [ 6, 11, 11,  7],
       [11, 11,  6,  5]])

In [43]:
arr1 > arr2

array([[False, False, False,  True],
       [ True,  True,  True,  True],
       [ True, False, False, False]])

# Numpy String Function

In [45]:
arr = np.array(['nikhil','yash'])

In [46]:
arr

array(['nikhil', 'yash'], dtype='<U6')

In [47]:
np.char.upper(arr)

array(['NIKHIL', 'YASH'], dtype='<U6')

In [48]:
np.char.title(arr)

array(['Nikhil', 'Yash'], dtype='<U6')

In [49]:
np.char.capitalize(arr)

array(['Nikhil', 'Yash'], dtype='<U6')

In [50]:
np.char.lower(arr)

array(['nikhil', 'yash'], dtype='<U6')

# Numpy - Mathematical Function

In [52]:
arr1

array([[2, 7, 8, 8],
       [6, 8, 9, 4],
       [9, 3, 4, 5]])

In [53]:
np.sin(arr1)

array([[ 0.90929743,  0.6569866 ,  0.98935825,  0.98935825],
       [-0.2794155 ,  0.98935825,  0.41211849, -0.7568025 ],
       [ 0.41211849,  0.14112001, -0.7568025 , -0.95892427]])

In [54]:
np.cos(arr1)

array([[-0.41614684,  0.75390225, -0.14550003, -0.14550003],
       [ 0.96017029, -0.14550003, -0.91113026, -0.65364362],
       [-0.91113026, -0.9899925 , -0.65364362,  0.28366219]])

In [55]:
np.tan(arr1)

array([[-2.18503986,  0.87144798, -6.79971146, -6.79971146],
       [-0.29100619, -6.79971146, -0.45231566,  1.15782128],
       [-0.45231566, -0.14254654,  1.15782128, -3.38051501]])

In [56]:
np.sinh(arr1)

array([[3.62686041e+00, 5.48316123e+02, 1.49047883e+03, 1.49047883e+03],
       [2.01713157e+02, 1.49047883e+03, 4.05154190e+03, 2.72899172e+01],
       [4.05154190e+03, 1.00178749e+01, 2.72899172e+01, 7.42032106e+01]])

In [57]:
np.tanh(arr1)

array([[0.96402758, 0.99999834, 0.99999977, 0.99999977],
       [0.99998771, 0.99999977, 0.99999997, 0.9993293 ],
       [0.99999997, 0.99505475, 0.9993293 , 0.9999092 ]])

In [58]:
np.log(arr1)

array([[0.69314718, 1.94591015, 2.07944154, 2.07944154],
       [1.79175947, 2.07944154, 2.19722458, 1.38629436],
       [2.19722458, 1.09861229, 1.38629436, 1.60943791]])

In [59]:
np.exp(arr1)

array([[7.38905610e+00, 1.09663316e+03, 2.98095799e+03, 2.98095799e+03],
       [4.03428793e+02, 2.98095799e+03, 8.10308393e+03, 5.45981500e+01],
       [8.10308393e+03, 2.00855369e+01, 5.45981500e+01, 1.48413159e+02]])

In [60]:
np.sqrt(arr1)

array([[1.41421356, 2.64575131, 2.82842712, 2.82842712],
       [2.44948974, 2.82842712, 3.        , 2.        ],
       [3.        , 1.73205081, 2.        , 2.23606798]])

In [61]:
np.power(arr1,2)

array([[ 4, 49, 64, 64],
       [36, 64, 81, 16],
       [81,  9, 16, 25]])

In [62]:
np.mean(arr1)

6.083333333333333

In [63]:
np.median(arr1)

6.5

In [66]:
np.std(arr1)

2.32588095615881

In [68]:
np.min(arr1)

2

In [69]:
np.max(arr1)

9