# Sort, Search & Counting Functions

In [1]:
import numpy as np

In [2]:
arr = np.array([4,2,3,5,86,1,25,36,45])

In [3]:
arr

array([ 4,  2,  3,  5, 86,  1, 25, 36, 45])

In [4]:
np.sort(arr)

array([ 1,  2,  3,  4,  5, 25, 36, 45, 86])

In [5]:
np.searchsorted(arr, 35)

4

In [6]:
arr1 = np.array([0,345,122,15,48,15,0,16,245,0])

In [7]:
np.count_nonzero(arr1)

7

In [8]:
arr

array([ 4,  2,  3,  5, 86,  1, 25, 36, 45])

In [10]:
np.where(arr > 6) # returns the indexes where the dATA IS GREATER THAN 6

(array([4, 6, 7, 8]),)

In [12]:
np.extract(arr > 6, arr)

array([86, 25, 36, 45])

In [13]:
arr

array([ 4,  2,  3,  5, 86,  1, 25, 36, 45])

In [15]:
arr.byteswap() # shows the byte data of the available elements

array([ 288230376151711744,  144115188075855872,  216172782113783808,
        360287970189639680, 6196953087261802496,   72057594037927936,
       1801439850948198400, 2594073385365405696, 3242591731706757120])

In [25]:
a = np.copy(arr) # this simply creates a deep copy where the new space is created and new variable is pointing it

In [17]:
a

array([ 4,  2,  3,  5, 86,  1, 25, 36, 45])

In [26]:
b = arr.view() # this creates a shallow copy where the new instance also references the same copy

In [20]:
b

array([ 4,  2,  3,  5, 86,  1, 25, 36, 45])

In [21]:
b[0]

4

In [22]:
b[0] = 69

In [23]:
b

array([69,  2,  3,  5, 86,  1, 25, 36, 45])

In [24]:
arr

array([69,  2,  3,  5, 86,  1, 25, 36, 45])

## Numpy Matrix Library

In [27]:
import numpy.matlib as nm

In [28]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [29]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [31]:
nm.eye(5) # for generating identity matrix

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [32]:
# Numpy Linera Algebra

In [33]:
arr1 = np.random.randint([[2,3],[4,5]])

In [34]:
arr1

array([[1, 1],
       [0, 0]])

In [35]:
arr2 = np.random.randint([[5,3],[2,5]])

In [36]:
arr2

array([[4, 2],
       [0, 2]])

In [37]:
np.dot(arr1,arr2)

array([[4, 4],
       [0, 0]])

In [38]:
arr1@arr2

array([[4, 4],
       [0, 0]])